name: "workspaces/controller: integration-tests"

permissions: {}

on:
  push:
    branches: [ "main", "notebooks-v2", "v*-branch" ]
  pull_request:
    paths: [ "workspaces/controller/**" ]
    branches: [ "main", "notebooks-v2", "v*-branch" ]

jobs:

  "integration-tests":
    runs-on: ubuntu-latest
    steps:

      # https://docs.k0sproject.io/v0.12.1/k0s-in-docker/#installation-steps
      - name: Start k0s
        run: docker run -d --name k0s --hostname k0s --privileged -v /mnt/k0s:/var/lib/k0s -p 6443:6443 docker.io/k0sproject/k0s:latest

      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build Notebook Controller Image
        run: |
          cd workflows/controller/
          make docker-build
        env:
          IMG: "pepa:zdepa"

      - name: Wait for k0s
      - run: |
          # wait for kubeconfig
          docker exec k0s sh -c 'until [ -f /var/lib/k0s/pki/admin.conf ]; do sleep 1; done'
          sleep 1

          mkdir -p $HOME/.kube
          docker cp k0s:/var/lib/k0s/pki/admin.conf $HOME/.kube/config
          until kubectl wait --for=condition=Ready nodes --all; do
            sleep 7
          done

      - name: Build & Apply manifests
        run: |
          cd workspaces/controller/config
          kubectl create namespace kubeflow

          export CURRENT_IMAGE="docker.io/kubeflownotebookswg/${IMG}"
          export PR_IMAGE="${IMG}:${TAG}"

          # escape "." in the image names, as it is a special characters in sed
          export CURRENT_IMAGE=$(echo "$CURRENT_IMAGE" | sed 's|\.|\\.|g')
          export PR_IMAGE=$(echo "$PR_IMAGE" | sed 's|\.|\\.|g')

          kustomize build overlays/kubeflow \
            | sed "s|${CURRENT_IMAGE}:[a-zA-Z0-9_.-]*|${PR_IMAGE}|g" \
            | kubectl apply -f -

          kubectl wait pods -n kubeflow -l app=workspace-controller --for=condition=Ready --timeout=300s
#
#      - name: Load Images into KinD Cluster
#      run: |
#        kind load docker-image "${IMG}:${TAG}"
#
#- name: Install kustomize
#  run: ./components/testing/gh-actions/install_kustomize.sh
#
#- name: Install Istio
#  run: ./components/testing/gh-actions/install_istio.sh
#
