name: "workspaces/controller: integration-tests"

permissions: {}

on:
  push:
    branches: [ "main", "notebooks-v2", "v*-branch" ]
  pull_request:
    paths: [ "workspaces/controller/**" ]
    branches: [ "main", "notebooks-v2", "v*-branch" ]

jobs:

  "integration-tests":
    runs-on: ubuntu-latest
    steps:

      # https://docs.k0sproject.io/v1.30.0+k0s.0/k0s-in-docker/#start-k0s
      - name: Start k0s
        run: docker run -d --name k0s --hostname k0s --privileged -v /mnt/k0s:/var/lib/k0s -p 6443:6443 --cgroupns=host docker.io/k0sproject/k0s:v1.30.0-k0s.0 -- k0s controller --enable-worker

      - uses: actions/checkout@v4

#      - uses: docker/setup-buildx-action@v3

      - name: Build Notebook Controller Image
        run: |
          cd workspaces/controller/
          make docker-build
        env:
          IMG: "pepa:zdepa"

      # https://docs.k0sproject.io/v1.30.0+k0s.0/airgap-install/#1-create-your-own-image-bundle-optional
      - name: Deploy image bundle into k0s
        run: |
          sudo docker image save pepa:zdepa -o /mnt/k0s/images/bundle_file
          docker container restart k0s

      - name: Wait for k0s
        run: |
          # wait for kubeconfig
          docker exec k0s sh -c 'until [ -f /var/lib/k0s/pki/admin.conf ]; do sleep 1; done'

          mkdir -p $HOME/.kube
          docker cp k0s:/var/lib/k0s/pki/admin.conf $HOME/.kube/config
          until kubectl wait --for=condition=Ready nodes --all; do
            sleep 3
          done

      - name: Build & Apply manifests
        run: |
          cd workspaces/controller/config

          # escape "." in the image names, as it is a special characters in sed
          export CURRENT_IMAGE=$(echo "$CURRENT_IMAGE" | sed 's|\.|\\.|g')
          export PR_IMAGE=$(echo "$PR_IMAGE" | sed 's|\.|\\.|g')

          kustomize build ./default \
            | sed "s|${CURRENT_IMAGE}:[a-zA-Z0-9_.-]*|${PR_IMAGE}|g" \
            | kubectl apply -f -

          # kubectl wait pods -n workspace-controller-system -l control-plane=workspace-controller --for=condition=Ready --timeout=300s
          until false; do
            kubectl describe deployments -n workspace-controller-system
            kubectl describe pods -n workspace-controller-system
            sleep 5;
          done
        env:
          CURRENT_IMAGE: "controller:latest"
          PR_IMAGE: "pepa:zdepa"

#      - name: Load Images into KinD Cluster
#      run: |
#        kind load docker-image "${IMG}:${TAG}"
#
#- name: Install kustomize
#  run: ./components/testing/gh-actions/install_kustomize.sh
#
#- name: Install Istio
#  run: ./components/testing/gh-actions/install_istio.sh
#
